package ca.credits.business.xiaohao;

import ca.credits.business.AbstractTemplate;
import ca.credits.business.enums.PlatformCodeEnum;
import ca.credits.common.config.Config;
import ca.credits.common.util.Md5Util;
import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Calendar;
import java.util.Date;

/**
 * Created by chenwen on 16/9/21.
 */
@DynamoDBTable(tableName="secret-number")
public class XiaohaoTemplate extends AbstractTemplate{
    public static String TABLE_NAME = Config.getString("aws.dynamodb.xiaohao.table.name");
    /**
     * 唯一主键 , 哈希序列，唯一标识该条记录
     */
    @DynamoDBHashKey(attributeName="primary_key")
    @DynamoDBAutoGeneratedKey
    private String primaryKey;

    /**
     * 手机号 , 15800353170
     */
    @DynamoDBAttribute(attributeName="phone")
    private String phone;

    /**
     * 平台编码 , 取值为‘X00001’
     */
    @DynamoDBAttribute(attributeName="plat_code")
    private String platCode;

    /**
     * 爬取时间 , yyyy-mm-dd hh:mm:ss
     */
    @DynamoDBAttribute(attributeName="crawl_time")
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    private Date crawlTime;

    /**
     * 删除日期 , yyyy-mm-dd hh:mm:ss
     */
    @DynamoDBAttribute(attributeName="jrjt_del_dt")
    private Date jrjtDelDt;

    public XiaohaoTemplate(PlatformCodeEnum.INameCode nameCode) {
        super(nameCode);
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.YEAR,10000);
        this.setJrjtDelDt(calendar.getTime());
        this.platCode = nameCode.getCode();
    }

    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey;
    }

    public String getPrimaryKey() {
        return this.primaryKey = this.primaryKey == null ? Md5Util.toMd5(this.phone + this.platCode) : this.primaryKey;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPlatCode() {
        return platCode;
    }

    public void setPlatCode(String platCode) {
        this.platCode = platCode;
    }

    public Date getCrawlTime() {
        return crawlTime;
    }

    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    public Date getJrjtDelDt() {
        return jrjtDelDt;
    }

    public void setJrjtDelDt(Date jrjtDelDt) {
        this.jrjtDelDt = jrjtDelDt;
    }
}
